### ISSUE TITLE
01 EnginePerform (Cook Modes) doesn't load 3 examples

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#28]
Branch: Dev
Sample: UESample01_EnginePerform (Cook Modes)

![image](https://user-images.githubusercontent.com/10253645/122260901-cb40a500-cea1-11eb-9398-a80a2d0ff1c0.png)

Can reproduce multiple times, just load both 01 by shooting at the second button while the 1st example is still loading (not sure If it's related, tbc)

**Comment by ddthejj** [comment]
Fixed in b6d9c5d19f135559e1c2e5115fa7eed86fa8e824

**Comment by jetXS** [comment]
tested and confirmed as fixed, thanks
