### ISSUE TITLE
UESample02_SimpleTexture - Can't assign a texture anymore in top_textureIn of details panel

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#29]
Branch: Dev
Sample: UESample02_SimpleTexture

![image](https://user-images.githubusercontent.com/10253645/122288109-aeb36580-cebf-11eb-82c7-eb4fd6fe2edd.png)

**Comment by ddthejj** [comment]
Fixed in a1fe121e1880de4cc00dc15eee2e48d5effdebf6

**Comment by jetXS** [comment]
tested and confirmed as fixed, thanks
