### ISSUE TITLE
UESample04_SimpleBlendCubeTexture - Can't clear a texture after assigning it

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#30]
Branch: Dev
Sample: UESample04_SimpleBlendCubeTexture

It seems to occur when the On/Off button was not shot at first and the Engine is not loaded

![image](https://user-images.githubusercontent.com/10253645/122288282-cb4f9d80-cebf-11eb-8a62-e902d5f5be13.png)

**Comment by ddthejj** [comment]
fixed in a1fe121e1880de4cc00dc15eee2e48d5effdebf6

**Comment by jetXS** [comment]
tested and confirmed as fixed, thanks
