### ISSUE TITLE
04 - Unassigning a texture should also propagate to TouchEngine

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#31]
![image](https://user-images.githubusercontent.com/10253645/122692599-180adf80-d204-11eb-98c9-aa1ad739530c.png)

@ddthejj correct me if I am wrong but I feel like it used to work

You can see in the above screenshot that while top_texA and top_texB are cleared, they are still passed to TouchEngine

Maybe to be confirmed w/ Tom, but I feel like you should be able to clear a TOP input (or any input) of any incoming data with the TouchEngine API.

**Comment by bangnoise** [comment]
Yes you can clear an input with the TouchEngine API.

**Comment by joydropDanielM** [comment]
Added in 706d534c69de6a8a08fdf211f4c5c488ba57bc6c

**Comment by ddthejj** [comment]
Added in ca7cb193cba4663b9c2d7ce8f14eefda94e1881a

**Comment by jetXS** [comment]
Tested and confirmed as fixed, thanks
