### ISSUE TITLE
08 - Collider doesn't destroy when unloading sample / engine

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#32]
![image](https://user-images.githubusercontent.com/10253645/122692744-c020a880-d204-11eb-990e-eedfffcfcab5.png)

Invisible collider 👻

**Comment by ddthejj** [comment]
Fixed in a08b94ba81e95f761cf0184eb03559e78ec4e0ec

**Comment by jetXS** [comment]
Tested and confirmed as fixed, thanks
