### ISSUE TITLE
User issue: Setting a string array as a DAT input doesn't seem to go through and be received by TouchEngine

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#33]
Branch: main (tag v0.9.2)
Sample: UESample03_Parameters

Should be able to test with 03 and debug the data flow by looking if the string array passed to the DAT input comes back on the other side through the DAT output, but also if Get Cells.. etc return the expected results.

[User post](https://forum.derivative.ca/t/touchengine-plugin-for-unreal-engine-beta-release/190764/15?u=jetxs):

> Is anyone else having trouble getting DAT input working? Using BP_TE_UESample03_Parameters from the sample project to send an array of strings into a DAT input does not seem to work. TOPs and CHOPs work just fine when sending data through and printing it back out in Unreal, but not DATs. When reading back the cell with Get Cell, I get the error “Accessed None trying to read property DAT”
> 
> [Here is a link to a test BP that uses UESample03_Parameters.tox from the sample](https://www.dropbox.com/s/lzn5z2td80htv82/BP_TE_UESample03_Parameters_DATTest.uasset?dl=0)
> 
> Also this is on 14010 and TouchEngine-UE4 0.9.2, UE 4.26.2

**Comment by ddthejj** [comment]
Fixed in e6768a24d4d9fe9fdc547485fa6e81bc25733f12

**Comment by jetXS** [comment]
Tested and confirmed as fixed.

Merged dev to main

Thanks
